# Run using `docker-compose up`
# Service only for development purposes
version: "3.7"

services:
  cl-es:
    container_name: cl-es
    image: elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
      - cluster.name=courtlistener-cluster
      - xpack.security.enabled=false
      - "http.cors.allow-origin=*"
      - "http.cors.enabled=true"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"
    ports:
      - "9200:9200"
    networks:
      - cl_net_overlay

  cl-django:
    depends_on:
      - cl-es